name: Build and Deploy using publish profile
on:
  push
    
env:
  AZURE_WEBAPP_NAME: infra-node-sample   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
     
    environment: dev
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
       
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run compile
        npm run build --if-present
        npm run test
    
    - name: 'Deploy to Azure WebApp'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_FREE_LEARN }}
        
    - uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
 # Azure logout 
    - name: logout
      run: |
        az logout
