name: nodeproject using service principle

on: [push]
env:
  AZURE_WEBAPP_NAME: serviceappservice  # set this to your application's name
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'npm install, build, and test'
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run compile
      
  
    - name: 'Deploy to Azure WebApp'
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZUE_CREDENTIAL_1 }}
       
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.serviceappservice }}
        package: .

    # Azure logout 
    - name: logout
      run: |
        az logout
