name: Testing HTTP Status

on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://infra-node-sample.azurewebsites.net/"]'
        expected: '[200]'
    - name: Set failure actions
      if: ${{ failure() }}
      env:
          DEPLOY_STATUS: FAIL
          
    - name: Set suceess actions
      if: ${{ success() }}
      env:
          DEPLOY_STATUS: SUCESS
   
