name: Testing HTTP Status

on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://infra-node-sample.azurewebsites.net/"]'
        expected: '[200]'
    - name: Set failure actions
      if: ${{ failure() }}
      run: echo ":("
      env:
          DEPLOY_STATUS: FAIL
          
    - name: Set suceess actions
      if: ${{ success() }}
      run: echo ":)"
      env:
          DEPLOY_STATUS: SUCESS
          
    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
        port: 465
        account: ${{secrets.MAIL_ID}}
        password: ${{secrets.PASS}}
        sender: Hashim
        from: ${{secrets.MAIL_ID}}
        to: ${{secrets.MAIL_ID}}
        subject: Deployment Status
        body: env.DEPLOY_STATUS

