name: Testing HTTP Status 2

on:
  workflow_dispatch:
   

jobs:
  review-app-test:
    runs-on: ubuntu-latest
    steps:

      # STEP: 1
      - name: Wait For HTTP Response of the Review App
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: https://infra-node-sample.azurewebsites.net/
          responseCode: '200,403'
          

      # STEP: 2
      - name: Set PR status to failure
        if: ${{ failure() }}
        run: echo ":("
